project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  # author: "Vlad Tesniere"
  favicon: "img/UCL_square.jpeg"
  navbar:
    logo: "img/ucl_logo.png"
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "CASA0023 Learning Diary"
    style: docked
    reader-mode: true
  repo-url: https://github.com/vtesniere/CASA0023_book
  repo-actions: issue
  google-analytics:
    tracking-id: "G-5LZK055F2X"
    anonymize-ip: true
  # date: "1/19/2023"
  chapters:
    - part: "Introduction and Helpful Tools"
      chapters:
      - index.qmd
      - abbreviations.qmd
    - part: "Using SNAP and understanding Landsat Data"
      chapters:
      - intro.qmd
      - 2_sensor_presentation.qmd
      - corrections.qmd
    - part: "GEE and Classification"
      chapters: 
        - GEE_intro.qmd
    - part: "Discussing Policy"
      chapters:
      - summary.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: img/Nighttime-purple.jpeg
    #cover-image: img/UCL_square.jpeg
  #css: textures.css
    theme: 
    # textures.css
        light: [cerulean, flatly]
        dark: [cerulean, darkly]
    code-link: true
  pdf:
    # documentclass: scrreprt
    documentclass: scrbook

editor: visual

