project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  # author: "Vlad Tesniere"
  navbar:
    logo: ucl_logo.png
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "CASA0023 Learning Diary"
    style: floating
    reader-mode: true
  repo-url: https://vtesniere.github.io/CASA0023_book/
  repo-actions: issue
  google-analytics:
    tracking-id: "G-5LZK055F2X"
    anonymize-ip: true
  # date: "1/19/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - 2_sensor_presentation.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cerulean, flatly]
        dark: [cerulean, darkly]
    code-link: true
  pdf:
    # documentclass: scrreprt
    documentclass: scrbook

editor: visual

