<div style="text-align: justify">

# Common Remote Sensing Abbreviations! {.unnumbered}

As remote sensing can get quite complex in terms of nomenclature, this abbreviation index can come in handy when potential concept explanations are not clear!

-   **RBG** : Red, Blue Green

-   **TOA** : Top of Atmosphere

-   **L-8** : Landsat-8 Satellite

-   **S-2** : Sentinel-2

-   **GEE** : Google Earth Engine

-   **SNAP** : Sentinel Application Platform is provided by the ESA/ESRIN and allows the Earth Observation Community with a free tool to process and analyse satellite imagery. It has the advantage of providing InSAR Processing capabilities, [which is not yet the case with GEE](https://gis.stackexchange.com/questions/348182/does-google-earth-engine-have-insar-processing-capabilities-for-sentinel-1-data#:~:text=The%20answer%20is%20no.,flexible%20python%2Dbased%20InSAR%20toolboxes)

-   **POI** : Points of Interest - these are points that are representative of certain land-cover types and allows for comparison between platforms. This was for example used in the [Bucharest Analysis](https://vtesniere.github.io/CASA0023_book/intro.html#Selecting-our-Points-of-Interest) where we used reference area for water, green area and industrial area to compare L-8 and S-2 imagery.

-   **ESA** : European Space Agency

-   **ESRIN** : ESA center for earth Observation created in 1966 and currently based in Frascati, Italy

-   **SWIR** : Short-wave infrared, part of the electromagnetic spectrum and allows for identification of objects invisible to the human eye and traditional multi-spectral bands. It can allow for the identification of certain terrain characteristics (i.e. certain bands in SWIR is more highly absorbed by water bodies). Ranges from 1.4 to 3 µm (micrometers)

-   **NIR** : Near infra-red

-   **DOS** : Dark Object Subtraction - Method to correct raw satellite imagery by considering the true value of the darkest pixel in the image as 0. If this is not the value of said pixel, this is attributed to variations caused by the atmosphere

-   **NDVI** : Normalised Difference Vegetation Index - Index determining the density of live vegetation in a particular area. The formula for this is: $$NDVI= \frac{NIR-Red}{NIR+Red}= \frac{Landsat B5 - Landsat B4} {Landsat B5 + Landsat B4}$$ The values range between -1 and 1: 0.1 and below considered low values, between 0.2 and 0.5 moderate values (i.e. shrubs and grass-land) and high values between 0.6 and 0.9 (typically dense vegetation, forests, fertile crops) @ndvith

-   **NDMI** : Normalised Difference Moisture Index - Similar methodology and interpretation to NDVI but here determines vegetation water content @normaliz . For Landsat 8-9, the formula is as follows: $$NDMI= \frac{NIR-SWIR}{NIR+SWIR}= \frac{Landsat B5 - Landsat B6} {Landsat B5 + Landsat B6}$$

-   **IFOV** : Instantaneous Field of View

-   **SAR** : Synthetic Aperture Radar

-   **Nadir** : celestial sphere directly below an observer

-   **Azimuth** : the direction of a celestial object from the observer, calculated through distance from horizon from a cardinal point (usually north or south)

-   **PCA** : Principal Component Analysis - is a method of unsupervised learning which aims to reduce the number of dimensions whilst still keeping most of the information. In remote sensing this is particularly useful as it can help understand and visualise where changes in terrain characteristics have taken place ( @munyati2004 )
