**Vlad Tesniere** [^index-1]

[^index-1]: Geo-spatial data scientist at the OECD environment directorate, UCL Department of Geography, MSc Social and Geographic Data Science, [LinkedIn](https://www.linkedin.com/in/vladimir-tesniere/)

::: callout-note
# Publications

Main /Co-author:

-   Monitoring land cover change to understand biodiversity pressures (DOI: <https://doi.org/10.1787/441a7a6c-en>, December 2024)

Conference Paper:

-   Leveraging advances in Language Models for neighbourhood delineation in the London housing market (DOI: <https://doi.org/10.5281/zenodo.10897775>, April 2024)

Contributor:

-   "OECD Regions and Cities at a glance 2024" (DOI: <https://doi.org/10.1787/f42db3bf-en>, December 2024)
:::

## Introduction and Presentation {.unnumbered}

Vlad's Blog and general thoughts on Remote Sensing Topics!

<!--The topics in this blog cover all material from CASA0023 led by Andrew Maclachlan. There are no numbers in the entries of the diary as the aim of this blog is to provide an overview of the different techniques used in remote sensing.-->

Although preferable to follow the blog entries in order, there should be sufficient information (with support from the '[Common Abbreviations](https://vtesniere.github.io/CASA0023_book/abbreviations.html)' page and various mouse-over explanations) to understand each individually.

I am currently working as a Geo-spatial data scientist at the OECD environment directorate, and a graduate of the Master's in Social and Geographic Data Science, at the Geography Department at UCL!

I come from a multi-cultural background, having Franco-Romania Heritage, and having had the opportunity to live in Paris, Bucharest, London and Syndey!

This blog was an opportunity for me to research topics that were of interest to me, therefore you may recognise certain reoccurring topics, such as the inclusion of Bucharest and Paris, two cities in which i have lived for the majority of my life!

Have fun reading and I hope you find as much interest reading, than I had researching these topics!

This work is a good representation of myself, as I aim to continue developing my skills in remote sensing, specially looking to find experience in Earth Observation and Policy Recommendation positions!

<!-- Other than working, I love a good hike with my sister and am a Bubble Tea fanatic (accurately represented by the Cat on the Right) although very costly to my student bank account -->

```{r echo=FALSE, include=FALSE, composites, fig.cap="After a pleasant walk in Timisoara (left) and a bubble tea loving cat (right)", fig.align='center', results='asis',fig.height=3, fig.width=6}
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
library(cowplot)
ggdraw() + draw_image('img/IMG_5443.heic', width = 0.5) + draw_image('img/IMG_5187.heic', width = 0.5, x = 0.5)
```
